#!/bin/sh

develop_branch="develop"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

# only check commit messages on main development branch
[ "$current_branch" != "$develop_branch" ] && exit 0

# regex to validate in commit msg
# if commiting to develop branch, must give:
  # highlight of issue
  # solution for the issue
commit_regex='(issue:\s.+\s-\ssolution:\s.+)|merge'
error_msg="Aborting commit. When pushing to develop, you must include the issue found and your implemented solution. (issue: [issue desc.] - solution: [solution desc.]"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi