#!/bin/sh

# get a list of all files that have been staged
# only files ending in the .ts extension are selected for validation
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\w+\.ts")

# if there are no staged files (empty) then exit with pass
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

# define the pass variable
PASS=true

echo "Starting linter..."

# for each file that has been staged
for FILE in $STAGED_FILES
do
  # run the in-built deno linter on the current file
  deno lint --unstable "$FILE"

  # if linter does not exit with an error, echo linter passed for the current file
  # else echo the file the the linter failed on, set passed to false
  if [[ "$?" == 0 ]]; then
    echo "o-DENO_LINT Passed: $FILE"
  else
    echo "x-DENO_LINT Failed: $FILE"
    PASS=false
  fi
done

echo "Linter complete."

# depending on if the linter failed, exit on corresponding code
if ! $PASS; then
  echo "The commit has failed. You must pass the linter validation before being able to commit. Please see the above message(s) for details."
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi

# if no errors exist with inputted status
exit $?